# Generated by Django 3.2.8 on 2022-10-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20220428_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='Imagen'),
        ),
    ]
